networks:
  fcgi_network:
    external: true


services: 
  fcgi: 
    image: nginx-fcgi:1.0
    build: ./fcgi/
    volumes:
      - ./fcgi/:/etc/nginx/
    container_name: fcgi_server
    networks:
      fcgi_network:
        ipv4_address: 172.20.0.2
    

  nginx: 
    image: nginx:latest
    build: ./nginx/
    volumes:
      - ./nginx/:/etc/nginx/
    container_name: nginx_server
    networks:
      fcgi_network:
        ipv4_address: 172.20.0.3
    ports: 
      - "80:8080"